### ISSUE TITLE
Cannot read property 'lookup' of undefined

### ISSUE THREAD

**Issue by mrinterweb** [kurko/ember-sync#29]
I am trying to get ember-localstorage-adapter working with ember-sync, ember 1.10, ember-cli 0.2.0. I upgraded to ember-data 1.0.0-beta.16. Anytime I try to access `this.emberSync.find('modelName', 1)`, I encounter this error.

```
TypeError: Cannot read property 'lookup' of undefined
    at ember$data$lib$system$serializer$$default.extend.transformFor (http://localhost:5000/assets/vendor.js:68222:39)
    at applyTransform (http://localhost:5000/assets/vendor.js:67257:32)
    at http://localhost:5000/assets/vendor.js:73911:20
    at Map.forEach.cb (http://localhost:5000/assets/vendor.js:23590:13)
    at OrderedSet.forEach (http://localhost:5000/assets/vendor.js:23381:13)
    at Map.forEach (http://localhost:5000/assets/vendor.js:23594:19)
    at Function.ember$data$lib$system$model$model$$default.reopenClass.eachTransformedAttribute (http://localhost:5000/assets/vendor.js:73910:84)
    at ember$data$lib$system$serializer$$default.extend.applyTransforms (http://localhost:5000/assets/vendor.js:67254:14)
    at ember$data$lib$serializers$json$serializer$$default.extend.normalize (http://localhost:5000/assets/vendor.js:68401:14)
    at superFunction [as _super] (http://localhost:5000/assets/vendor.js:23784:22)
```

It looks like the application adapter is not available. Is this likely a problem with my configuration of ember-localstorage-adapter or ember-sync?

**Comment by mrinterweb** [comment]
After digging a bit more, I realized that the ActiveModelAdapter I am using works as expected. I see requests and responses from my backend server. It is just having problems with the serialization. I copied and pasted the configuration examples from the ember-sync README file. Not sure what is wrong.

**Comment by kurko** [comment]
I have a hunch: you misspelled something in your model. Can you paste it here?

Basically, transformFor will  check what you're using in your DS.attr(transform). If you use "string", it will load the appropriate object. In your case, it looks like it's trying to find a transform that doesn't exist.

**Comment by mrinterweb** [comment]
I'm no longer using ember-sync so I won't be able to confirm fixes so I'm closing the issue.
